version: "3.7"

services:
  src:
    build:
      context: .
      dockerfile: Dockerfile_src.dockerfile
    volumes:
      - sources:/app

  db:
    image: postgres:12-alpine
    container_name: cin_db
    env_file:
      - .env
    networks:
      - internal
    volumes:
      - /psql_db/postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    build:
      context: .
      target: production_build
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: cin_sever
    working_dir: /app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
    depends_on:
      - src
      - db
    ports:
      - "80:80"
    networks:
      - internal
    volumes:
      - sources:/app

  adminer:
    image: adminer
    container_name: fast_cin_admin
    ports:
      - "8080:8080"

volumes:
  sources:

networks:
  internal:
    driver: bridge